import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class NewMessage extends StatefulWidget {
  const NewMessage({super.key});

  @override
  State<NewMessage> createState() => _NewMessageState();
}

class _NewMessageState extends State<NewMessage> {
  final _messageController = TextEditingController();

  @override
  void dispose() {
    _messageController.dispose();
    super.dispose();
  }

  void _submitMessage() async {
    final enteredMessage = _messageController.text;

    if (enteredMessage.trim().isEmpty){
      return;
    }

    FocusScope.of(context).unfocus();   //This will close any open keyboard immediately.. 
    _messageController.clear();  //This will clear Textfield immediately after sending..

    //Sending & Reading Data To & From Firebase..
    final user = FirebaseAuth.instance.currentUser!;  //This gives access to currently logged-in user.
    final userData = await FirebaseFirestore.instance
        .collection('users')
        .doc(user.uid)
        .get();  

    FirebaseFirestore.instance.collection('chat').add({  // Add method gives unique Id as a name generated by firebase.
      'text' : enteredMessage,
      'createdAt' : Timestamp.now(),
      'userId' : user.uid,
      'username' : userData.data()!['username'],
      'userImage' : userData.data()!['image_url'],
    });    
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(right: 1, left: 15, bottom: 14,),
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: _messageController,
              textCapitalization: TextCapitalization.sentences,
              autocorrect: true,
              enableSuggestions: true,
              decoration: const InputDecoration(labelText: 'Send a message...'),
            ),
          ),

          IconButton(
            onPressed: _submitMessage, 
            icon: const Icon(Icons.send),
            color: Theme.of(context).colorScheme.primary,
          )
        ],
      ),
    );
  }
}